### ISSUE TITLE
Azure AD Version

### ISSUE THREAD

**Issue by bradyjoslin** [signalnerve/workers-auth0-example#7]
Hey @signalnerve - thanks for this example and the associated walkthrough in the docs!

I've had a need to integrate auth with workers using Azure AD and with just a few modifications to this example was able to get that working pretty easily.  The Azure AD version can be found here:
https://github.com/bradyjoslin/workers-azuread-example

I'll likely create an Okta version sometime later this year.

**Brainstorming...** perhaps ambitious, but since most of the code is the same across identity providers, this could be genericized into a "workers-auth" library for worker projects, providing cross-IdP support.  The actual IdP used by a given project could be set through configuration.

But, for now, this is fantastic and definitely opens up my ability to further leverage the Workers platform.

**Comment by signalnerve** [comment]
wow @bradyjoslin this is awesome!!!

> Brainstorming... perhaps ambitious, but since most of the code is the same across identity providers, this could be genericized into a "workers-auth" library for worker projects, providing cross-IdP support. The actual IdP used by a given project could be set through configuration.

have felt similarly about this :) just created https://github.com/signalnerve/workers-auth for this, i think it's a fantastic idea
